### ISSUE TITLE
Deprecated features used

### ISSUE THREAD

**Issue by tiago-cruz-movile** [chef-cookbooks/push-jobs#134]
### Cookbook version
5.1.2

### Chef-client version
12.20.3

### Platform Details
CentOS 7

### Scenario:
Remove "Deprecated features used!" messages

### Steps to Reproduce:
Run "chef-client -o push-jobs"

### Expected Result:
No "deprecated" message

### Actual Result:

```
Deprecated features used!
  Cloning resource attributes for service[chef-push-jobs-client] from prior resource
Previous service[chef-push-jobs-client]: /var/cache/chef/cookbooks/push-jobs/resources/service_systemd.rb:85:in `create_init'
Current  service[chef-push-jobs-client]: /var/cache/chef/cookbooks/push-jobs/resources/service_systemd.rb:72:in `block in class_from_file' at 1 location:
    - /var/cache/chef/cookbooks/push-jobs/resources/service_systemd.rb:72:in `block in class_from_file'
   See https://docs.chef.io/deprecations_resource_cloning.html for further details.
  Cloning resource attributes for service[chef-push-jobs-client] from prior resource
Previous service[chef-push-jobs-client]: /var/cache/chef/cookbooks/push-jobs/resources/service_systemd.rb:85:in `create_init'
Current  service[chef-push-jobs-client]: /var/cache/chef/cookbooks/push-jobs/resources/service_systemd.rb:39:in `block in class_from_file' at 1 location:
    - /var/cache/chef/cookbooks/push-jobs/resources/service_systemd.rb:39:in `block in class_from_file'
   See https://docs.chef.io/deprecations_resource_cloning.html for further details.

```

**Comment by tas50** [comment]
This one isn't actually an issue even though it is technically resource cloning. It's one of those deprecation that warn you about something that *could* be an issue. The problem is it breaks pipelines that have the fail on deprecation flag in test kitchen enabled. I'll see if I can work some magic to fix it for those.
